### ISSUE TITLE
Problem using Integram Notifier

### ISSUE THREAD

**Issue by Veyozei** [CryptoSignal/crypto-signal#197]
Successfully added Integram Notifier to Telegram Channel using @integram_bot using command
NOTIFIERS_INTEGRAM_REQUIRED_URL=

Although as soon as I launch I get a few pairs sent to the channel telling the pairs wether its hot or cold from all the indicators but it only sends out a few then the bot crashes. Gives me the following error code:

My guess is maybe the program sends out too many messages and gets blocked for anti-spam, which causes the program to think that something is wrong, gives you an error like "Too many requests" .. This is just a speculation, I am not a programmer, just a thought...

Good luck !

Traceback (most recent call last):
  File "app.py", line 46, in <module>
    main()
  File "app.py", line 41, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 56, in run
    self.test_strategies(market_data, output_mode)
  File "/app/behaviour.py", line 144, in test_strategies
    self.notifier.notify_all(message)
  File "/app/notification.py", line 81, in notify_all
    self.notify_integram(message)
  File "/app/notification.py", line 124, in notify_integram
    self.integram_client.notify(message)
  File "/app/notifiers/integram_client.py", line 38, in notify
    urllib.request.urlopen(req, jsondataasbytes)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

**Comment by kelvinrrivera** [comment]
I have the same issue.

**Comment by shads2** [comment]
We'll try to fix this as soon as we can

**Comment by shads2** [comment]
ich, I just looked at our telegram code. I am probably going to do some significant refactoring to hopefully make it better all round.

**Comment by shads2** [comment]
Fixed in https://github.com/CryptoSignal/crypto-signal/pull/205/ waiting for review, this is a significant change to the telegram integration and completely changes how it works. Existing users will need to update their config.

**Comment by Veyozei** [comment]
So I tried updated the application, seemed to work fine, I havn't changed anything in the folder from the previous version, leaving my old settings.env file in there with my old setup using Binance exchange and Integram Notifier. 
Still get the same error message so what am I doing wrong ?

**Comment by shads2** [comment]
The change hasn't been merged yet. It's still waiting for review.

**Comment by shads2** [comment]
Merged, build should publish in the next hour.
